/**
 * Generated by `npm run theme` from scripts/theme/palette.mjs. Do not edit.
 *
 * The themes as the settings page lists them: what each one is called, which
 * group it belongs under, and the three colours its card is painted with.
 */

export type ThemeId =
  | 'slate'
  | 'fjord'
  | 'pine'
  | 'dusk'
  | 'plum'
  | 'moss'
  | 'ink'
  | 'obsidian'
  | 'mono'
  | 'void'
  | 'jade'
  | 'crimson'
  | 'ember'
  | 'paper'
  | 'mist'
  | 'sand'
  | 'frost'
  | 'lilac'

export interface Theme {
  id: ThemeId
  name: string
  /** The group it belongs to, shown over the swatches. */
  kind: 'Light' | 'Semi-dark' | 'Dark'
  /** One line on what it is for. */
  note: string
  /** Background, accent, text — the three colours a card is painted with. */
  swatch: [string, string, string]
}

export const THEMES: Theme[] = [
  {
    id: 'slate',
    name: 'Slate',
    kind: 'Semi-dark',
    note: 'The default: a cool grey window with a blue accent.',
    swatch: ['#14181d', '#4f9cf9', '#d4dde9']
  },
  {
    id: 'fjord',
    name: 'Fjord',
    kind: 'Semi-dark',
    note: 'Slate with more blue in the ground.',
    swatch: ['#121b24', '#42addf', '#d5e1ec']
  },
  {
    id: 'pine',
    name: 'Pine',
    kind: 'Semi-dark',
    note: 'A green-grey window; the accent is a deep teal.',
    swatch: ['#0a1410', '#3ebca5', '#cadbd4']
  },
  {
    id: 'dusk',
    name: 'Dusk',
    kind: 'Semi-dark',
    note: 'Warm grey, with a violet accent.',
    swatch: ['#1c1920', '#a787ef', '#e4ddea']
  },
  {
    id: 'plum',
    name: 'Plum',
    kind: 'Semi-dark',
    note: 'A purple-tinted window and a pink accent.',
    swatch: ['#1d141d', '#ea7ab2', '#e4d8e3']
  },
  {
    id: 'moss',
    name: 'Moss',
    kind: 'Semi-dark',
    note: 'An olive window with a lime accent.',
    swatch: ['#161b11', '#9bcf59', '#dae0d3']
  },
  {
    id: 'ink',
    name: 'Ink',
    kind: 'Semi-dark',
    note: 'Nearly black, with a colder blue.',
    swatch: ['#0b0f15', '#459ced', '#ccd6e2']
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    kind: 'Dark',
    note: 'Neutral charcoal, no colour in the ground at all.',
    swatch: ['#09090a', '#5295ec', '#d0d1d4']
  },
  {
    id: 'mono',
    name: 'Mono',
    kind: 'Dark',
    note: 'Grey, and one colour: everything that is not meaning is grey.',
    swatch: ['#0a0a0a', '#e5e5e7', '#d2d2d2']
  },
  {
    id: 'void',
    name: 'Void',
    kind: 'Dark',
    note: 'Pure black, with a cyan accent.',
    swatch: ['#000000', '#37b9c7', '#cccccc']
  },
  {
    id: 'jade',
    name: 'Jade',
    kind: 'Dark',
    note: 'Black, lit green — the additions move yellow to stay apart from it.',
    swatch: ['#000000', '#49df71', '#cccccc']
  },
  {
    id: 'crimson',
    name: 'Crimson',
    kind: 'Dark',
    note: 'Black, lit red — a deletion keeps a redder red to stay apart.',
    swatch: ['#000000', '#fa4a52', '#cccccc']
  },
  {
    id: 'ember',
    name: 'Ember',
    kind: 'Dark',
    note: 'Black, lit amber — a warning moves yellower to stay apart.',
    swatch: ['#000000', '#fa8c31', '#cccccc']
  },
  {
    id: 'paper',
    name: 'Paper',
    kind: 'Light',
    note: 'Plain white, blue accent.',
    swatch: ['#ffffff', '#2476d6', '#313131']
  },
  {
    id: 'mist',
    name: 'Mist',
    kind: 'Light',
    note: 'A cool off-white, easier on the eyes than plain white.',
    swatch: ['#eff1f5', '#3373d6', '#26282d']
  },
  {
    id: 'sand',
    name: 'Sand',
    kind: 'Light',
    note: 'Warm paper, for people who find white screens cold.',
    swatch: ['#faf7ef', '#2677c1', '#302c22']
  },
  {
    id: 'frost',
    name: 'Frost',
    kind: 'Light',
    note: 'Pale blue paper with a teal accent.',
    swatch: ['#f2fbfe', '#05809c', '#242f32']
  },
  {
    id: 'lilac',
    name: 'Lilac',
    kind: 'Light',
    note: 'Pale violet paper, purple accent.',
    swatch: ['#fbf9fe', '#763fcc', '#312c36']
  }
]
